<a href="https://colab.research.google.com/github/lawbaker/PythonOR2021/blob/main/01.1_OR_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operations Research 2021 TA Session 2.1: Linear Algebra in Python

## Lawrence Baker

## Sessions
1.   An introduction to python (and colab)
2.   **Linear algebra** & unconstrained convex optimization problems
3.   Constraints and integer programming
4.   *TBD - Networks? Dataframes? What do you want?*
5.   An introduction to machine learning

# Introduction

For some of our OR problems we basically want to use python as a fancy calculator that can handle linear algebra. The alternative used in the 'normal' OR class is Octave, which is a GNU (free) version of Matlab.

In this session we'll cover arrays and how to manipulate them like matrices. I'll also show you how to use markdown for mathematical formulas and we'll do some practice questions

# Packages

From now on we're going to import all the packages we need at the top of the code. This is generally accepted practice. If you get half way through writing a file and you realise you need a new package, go back and import it at the top.

In [ ]:
import numpy as np
import numpy.linalg as la

# NumPy arrays

There is no base support for arrays/matrices in python, instead we reply on NumPy. The closest you can get in base python is a list, you might think we can write the horizontal vector:

$H =
 \begin{pmatrix}
  3 & 19 
 \end{pmatrix}$

 As a list 

 ```
H = [3, 19]
 ```
But this doesn't act the way we want it to, instead we have to initalize this object as an NumPy array, which is a list of lists which understands that you are specifying spacially ordered data. An array made with a single list-level is a vector.

In [ ]:
H = np.array([3, 19])

H

array([ 3, 19])

You can also specify multidimensional arrays (for our purposes, these are matrices). Here are two ways of specifying a matrix using a list of lists. They are identical in terms of code but I strongly recommend the second for readability.

In [ ]:
M1 = np.array([[1 ,2 ,3], [4, 5, 6], [7, 8, 9]])
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M2 = np.array([[1 ,2 ,3], 
               [4, 5, 6], 
               [7, 8, 9]])
M2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

If you want to know the dimensions of an array you have created, then you can use the .shape method. This produces a tuple with (num_rows, num_cols)

In [ ]:
M2.shape

(3, 3)

In [ ]:
H.shape

(2,)

You will notice that, for the vector H, only a single dimension is displayed. This is intentional and is not normally an issue, but if it ever is then you can always use reshape or specify it deliberately as a two dimensional array using a list of lists.

In [ ]:
HR = H.reshape(1, 2)

HR.shape

(1, 2)

In [ ]:
HS = np.array([[3, 19]])

HS.shape

(1, 2)

In [ ]:
HS

array([[ 3, 19]])

## Initializing Arrays: Exercise

That's basically all there is to creating arrays. Some practice:

Make this guy twice, once as a matrix, once as a vector:

$ \begin{pmatrix}
  3 & 19 & 7 & 2
 \end{pmatrix}$

Then this one:

 $\begin{pmatrix}
  1 & 0 \\
  0 & 1
 \end{pmatrix}$

 And finally
 
 $\begin{pmatrix}
  6  \\
  23 \\
  56 \\
  3  \\
  12 \\
 \end{pmatrix}$

In [ ]:
np.random.randint(1,10)

7

# Linear Algreba - Manipulating Arrays

##Indexing and Selection

In [ ]:
## Creates an array that runs 0 to 99
a = np.arange(0,1000,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380,
       390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510,
       520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640,
       650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770,
       780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900,
       910, 920, 930, 940, 950, 960, 970, 980, 990])

We can select along our 1D array using the syntax
```
array[start:finish:step]
```

As with other python indexing, this is 0 indexed, and ranges include the beginning but are exclusive of the end.


In [ ]:
a[60:80:3]

array([600, 630, 660, 690, 720, 750, 780])

Use negative numbers to indicate that you are reading from the end. So -1 does everything except the final number

In [ ]:
a[80:-1:2]

array([800, 820, 840, 860, 880, 900, 920, 940, 960, 980])

Or leave it blank to indicate you want everything along that dimension (default step is 1)

In [ ]:
a[87:]

array([870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990])

This is identical to:

In [ ]:
a[87:a.size:1]

array([87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
a[87:a.shape[0]:1]

array([87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Let's reshape this into a 10 x 10 2D array

In [ ]:
b = a.reshape(10,10)
b

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])

We use the same selection syntax in two directions.

```
array[rowstart:rowfinish:rowstep, colstart:colfinish:colstep]
```

In [ ]:
b[2:5, 3:9]

array([[230, 240, 250, 260, 270, 280],
       [330, 340, 350, 360, 370, 380],
       [430, 440, 450, 460, 470, 480]])

## Array Selection: Exercise

Create an 10 by 5 array that goes from 3 to 983 in steps of 20.

Select a square from the array with corners:

$$\begin{pmatrix}
  323 & \cdots & 363 \\
  \vdots & \ddots & \vdots  \\
  723 & \cdots & 763 \\
 \end{pmatrix}$$

## Norms

The l2 norm (which is the norm we will be using) of a vector is how long that vector would be if it was drawn out in euclidian space. In two dimensions this is basically pythagoras:

$$V =  \begin{pmatrix}
  x  \\
  y \\
 \end{pmatrix}$$

$$||V||_2 = \sqrt{x^2 + y^2}$$

Fortunately, this extends to multiple dimensions too:

$$\textbf{x} =  \begin{pmatrix}
  x_1  \\
  x_2  \\
  x_3  \\
  \vdots  \\
  x_n  \\
 \end{pmatrix}$$

$$||\textbf{x}||_2 = \sqrt{x_1^2 + x_2^2 + x_3^2 + ... + x_n^2}$$

To find the norm quickly we can use [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html):

In [ ]:
P = np.array([3, 4])
P

array([3, 4])

In [ ]:
la.norm(P)

5.0

In [ ]:
la.norm(np.array([3, 4, 5, 6, 7, 8, 9]))

16.73320053068151

I've needed to use it, but if you give numpy.linalg.norm a matrix, then it will return the square root of the sum of the squares of every element. This is nice because it doesn't matter if you define your vectors as 1D or 2D.

## Transpose

We can take a transpose by using the .T attribute



In [ ]:
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
HR

array([[ 3, 19]])

In [ ]:
HR.T

array([[ 3],
       [19]])

Remember that these changes do not automatically make their way through to an object, unless you use assignment. HR stays the same.

In [ ]:
HR

array([[ 3, 19]])

Transpose won't work with a vector (only matrices)

In [ ]:
H

array([ 3, 19])

In [ ]:
H.T

array([ 3, 19])

## Matrix Multiplication

It will be tempting to use '*' for matrix multiplication, but this gives us elementwise multiplication, we want to use @ instead.

In [ ]:
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M1 * M1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
M1 @ M1

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

You can also use [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) or [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html), which for our purposes are the same.

In [ ]:
np.dot(M1, M1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
np.matmul(M1, M1)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

## Matrix powers

Many array uses have bitwise operations in mind, so again we have to be careful when raising to the power. Simply using '**' will return the square of each element.

In [ ]:
M1**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

Instead we should use [numpy.linalg.matrix_power](https://numpy.org/doc/stable/reference/generated/numpy.linalg.matrix_power.html).

Remember that we abbreviated numpy.linalg as la when we imported it.

In [ ]:
la.matrix_power(M1, 2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
la.matrix_power(M1, 200)

array([[  239112876697182416, -8777635175808341736,   652360845395685728],
       [ 7800880526646967310,  6866766341019846025,  5932652155392724740],
       [-3084095897112799412,  4064423784138482170, -7233800608319787864]])

## Inverse and Determinants

You know the drill by now.

[Determinants](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html)

[Inverse](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)


In [ ]:
M3 = np.array([[-2 ,-4 ,2], 
               [-2, 1, 2], 
               [4, 2, 5]])

la.det(M3)

-90.0

In [ ]:
la.inv(M3)

array([[-0.01111111, -0.26666667,  0.11111111],
       [-0.2       ,  0.2       , -0.        ],
       [ 0.08888889,  0.13333333,  0.11111111]])

## Eigenvalues and Eigenvectors

Eigenvalues and Eigenvectors are magic, but we don't really need to know them for this course. They are cool and useful concept and I highly recommend the [3Blue1Brown video](https://www.youtube.com/watch?v=PFDu9oVAE-g) on them (and associated series).

The short explanation is that we can think of matrices as transformations in space, a 2x2 matrix specifies a transformation in 2D space, an NxN matrix in ND space. These transformations are a series of rotatations, shears, and stretches (or compressions). Some stretches are bigger than others. If we keep applying the same transformation over time then eventually the biggest stretch will dominate and the resultant vector will always point in this direction. This vector is the eigenvector.

For our purposes you just need to know [numpy.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)

In [ ]:
la.eig(M3)

(array([-5.,  3.,  6.]), array([[ 0.81649658,  0.53452248,  0.05842062],
        [ 0.40824829, -0.80178373,  0.35052374],
        [-0.40824829, -0.26726124,  0.93472998]]))

Ah, one function can produce two objects, luckly we can assign two objects at once too.

In [ ]:
eigval_M3, eigvec_M3 = la.eig(M3)

In [ ]:
eigval_M3

array([-5.,  3.,  6.])

In [ ]:
eigvec_M3

array([[ 0.81649658,  0.53452248,  0.05842062],
       [ 0.40824829, -0.80178373,  0.35052374],
       [-0.40824829, -0.26726124,  0.93472998]])

If we wanted to find the eigenvector corresponding to the largest eigenvalue:

In [ ]:
#Find the index of the biggest absolute value
i = np.argmax(abs(eigval_M3))

##Find the corresponding eigenvector
eigvec_M3[i]

In [ ]:
##Or all on one line
eigvec_M3[np.argmax(abs(eigval_M3))]

Finally, one last tip for the below exercise. We can diagonalize a vector to turn it into a square matrix with values only on the diagonal.

In [ ]:
eigval_M3

array([-5.,  3.,  6.])

In [ ]:
np.diag(eigval_M3)

array([[-5.,  0.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  0.,  6.]])

## Linear Algebra: Exercise

It's a very useful result result that for any real symmetric matrix, $A$, we can decompose it into it's eigenvalues and eigenvectors. Such that:

$$A = Q \Lambda Q^{-1}$$

Where $Q$ is the matrix of eigenvectors and $\Lambda$ is a diagonal matrix of the corresponding eigenvalues.

For the matrix

 $\begin{pmatrix}
  7  & 0  & 12 \\
  0  & 3  & -6 \\
  12 & -6 & 1.1
 \end{pmatrix}$

 Find $Q$, $\Lambda$, and prove that the above theorem holds for this matrix.

In [ ]:
M4 = np.array([[7,  0,  12],
               [0,  3,  -6],
               [12, -6, 1.1]])

M4

array([[ 7. ,  0. , 12. ],
       [ 0. ,  3. , -6. ],
       [12. , -6. ,  1.1]])

In [ ]:
eigval_M4, Q = la.eig(M4)

lamb = np.diag(eigval_M4)

Q_inv = la.inv(Q)

In [ ]:
Q @ lamb @ Q_inv

array([[ 7.00000000e+00,  5.41384852e-16,  1.20000000e+01],
       [ 3.32627195e-16,  3.00000000e+00, -6.00000000e+00],
       [ 1.20000000e+01, -6.00000000e+00,  1.10000000e+00]])

As part of eigenvector magic it's also true that 

$$A = Q \Lambda Q^{T}$$

Modify the above code to check this holds too!

Finally, you might notice that there are some small rounding errors occuring due to machine precision. The base python function for rounding is round(). But this doesn't work for arrays. Google to find the correct function and round to two decimal places.

In [ ]:
Q @ lamb @ Q.T

array([[ 7.00000000e+00,  0.00000000e+00,  1.20000000e+01],
       [-2.22044605e-16,  3.00000000e+00, -6.00000000e+00],
       [ 1.20000000e+01, -6.00000000e+00,  1.10000000e+00]])

In [ ]:
np.around(Q @ lamb @ Q.T)

array([[ 7.,  0., 12.],
       [-0.,  3., -6.],
       [12., -6.,  1.]])